### ISSUE TITLE
default is not exported

### ISSUE THREAD

**Issue by felluksch** [hurtigruten/svelte-table#28]
Hi,
rollup can't handle `import SvelteTable from '@hurtigruten/svelte-table';` because "'default' is not exported by svelte-table".
See [Svelte REPL](https://svelte.dev/repl/6b54adcf4c4d4692b3feb17a8050ce13?version=3.46.4), same behaviour on local machine.

**Comment by neonwarp** [comment]
Thank you for the info, indeed there is no default import. You can use it by `import { SvelteTable } from '@hurtigruten/svelte-table';`
