### ISSUE TITLE
Custom pagination classes not applying

### ISSUE THREAD

**Issue by Gildedter** [hurtigruten/svelte-table#32]
been setting `paginationContainer`, `paginationInfo` & `paginationButtons`, but none of them are applying, I'm using tailwind-css ([flowbite](https://flowbite.com)), specifically tried applying [this](https://flowbite.com/docs/components/button-group/) for the navigation buttons

**Comment by neonwarp** [comment]
Can you please provide more information? Maybe a REPL? I tried to apply the classes you linked and all seems to work just fine.

https://svelte.dev/repl/6fb0dfd0a0ee4627a33c6ab434e81b67?version=3.47.0

**Comment by bartektelec** [comment]
You can also use the `pagination` slot for more control, in my mind this often makes styling easier as you can move your pagination to a separate component. See this example

https://svelte.dev/repl/5cbe228d3cad47f18541c505c9e4b5de?version=3.47.0

More about it:
https://github.com/hurtigruten/svelte-table/blob/main/docs/pagination/index.md#custom-pagination-component
https://github.com/hurtigruten/svelte-table/blob/main/docs/slots/pagination.md
