### ISSUE TITLE
Make cell "Editable"

### ISSUE THREAD

**Issue by Gildedter** [hurtigruten/svelte-table#34]
How do I target a specific cell (row and column) to be a text box when clicked and edit its contents?

**Comment by neonwarp** [comment]
Hi, this is a feature request already https://github.com/hurtigruten/svelte-table/issues/23. There is no actual plan for it yet but I guess you can use the slots to generate a custom key for each row/cell, something like this https://svelte.dev/repl/1bc1cc9a18334312bdb5f7d3e78abdec?version=3.48.0
