### ISSUE TITLE
Add docs examples for expanded rows, maybe REPL demos would be nice?

### ISSUE THREAD

**Issue by Gildedter** [hurtigruten/svelte-table#35]
Specifically for expanded rows, been using this with a modal button column since I couldn't make the expanded row function work

**Comment by bartektelec** [comment]
In order to make expanded rows working you will need to programmatically set `row.isExpanded` for the row you want expanded, and then handle the rest in the "expanded" slot, there you have access to the `row` itself if needed.
You can for example bind a click handler for a whole row (or only a specific cell if you want) and set `isExpanded` to true for that one row. We don't do that in the lib itself, because some people will want different behaviour - either closing all other rows when expanding one, or only listening to click on one cell and not whole row, here it is up to you. Hope it helped.

I don't think we are planning on adding any demos besides examples in the docs MD files - which I can see lack one for expanding rows, if you want to contribute with that feel free to open a PR it would be appreciated

**Comment by Gildedter** [comment]
> 

will try this, thanks

**Comment by Gildedter** [comment]
It worked like you said, only problem now is there's a slight delay from click to expanding

```
/// script
  const handleRowClick = (e) => {
    e.detail.row.isExpanded = true;
  };
  
///  body
  <SvelteTable
    {...tableDefaults}
    let:cell
    let:column
    let:row
    on:clickRow={handleRowClick}
  >
      <div slot="cell">{cell}</div>
      <div slot="expanded">Never Gonna Give You Up</div>
  </SvelteTable>
```

**Comment by bartektelec** [comment]
Hi,
I'm not really sure why there would be a performance issue (or delay of any other kind)
looking at the snippet you provided you need to remember how Svelte treats reactivity:
mutating objects and its values is not a recommended way of updating a state, try assigning a new reference to it instead.

https://svelte.dev/tutorial/updating-arrays-and-objects

i.e
```ts
const handleTableRowClick = (response) => {
    const clickedRow = response.detail.row;

    rows = rows.map((row) =>
      row === clickedRow
        ? { ...row, isExpanded: true }
        : row
    );
  };
```

**Comment by Gildedter** [comment]
> Hi, I'm not really sure why there would be a performance issue (or delay of any other kind) looking at the snippet you provided you need to remember how Svelte treats reactivity: mutating objects and its values is not a recommended way of updating a state, try assigning a new reference to it instead.
> 
> https://svelte.dev/tutorial/updating-arrays-and-objects
> 
> i.e
> 
> ```ts
> const handleTableRowClick = (response) => {
>     const clickedRow = response.detail.row;
> 
>     rows = rows.map((row) =>
>       row === clickedRow
>         ? { ...row, isExpanded: true }
>         : row
>     );
>   };
> ```

Thanks that solved the delay issue, now my current problem is, the expanded slot only renders on the first column:

```
// script
  const handleRowClick = (e) => {
    const clickedRow = e.detail.row;
    loansTable.rows = loansTable.rows.map((r) =>
      r === clickedRow ? { ...r, isExpanded: !r.isExpanded } : r
    );
  };
  
// body
  <SvelteTable
    {...tableDefaults}
    let:cell
    let:column
    let:row
    on:clickRow={handleRowClick}
  >
    <div slot="cell">
      {#if column.key === "stop"}
        <span>{row.stop === "1" ? "Yes" : "No"}</span>
      {:else}
        <span>{cell}</span>
      {/if}
    </div>
    <div slot="expanded">
      <SvelteTableWrapper source={row.arrayColumn} /> //
    </div>
  </SvelteTable>
```
where, I have a column that holds an object array (passed via an event), I'm rendering a table inside the expanded slot (a nested svelte table)

Edit 1: Solved it with this "janky" solution:
```
    <tr slot="expanded">
      <td colspan={tableDefaults.columns.length}>
        <SvelteTableWrapper source={row.guarantors} />
      </td>
    </tr>
```

**Comment by bartektelec** [comment]
The way you solved is pretty much the best solution, we are not planning on "guessing" what the user wants to insert in their expanded row, so you can insert as many `<td>` as you want and ensure that the cell widths match the rest of the table, thats why inserting one `<td>` will only fill one column and to stretch it out you will need to use `colspan` attribute. The `expanded` slot will be inserted to the markup right after the row that has been expanded and is a part of the whole table.

It may not be objectively best or easiest, but it's a way we found to give most customization abilities to the user, this way you can have expanded row's cells that are merged in any way, stretched or just keep it the same way as all unexpanded rows.

**Comment by bartektelec** [comment]
Live demo with expanded rows, fetching data, async pagination added to the README
