### ISSUE TITLE
Conditional styling for row

### ISSUE THREAD

**Issue by Gildedter** [hurtigruten/svelte-table#39]
I have a `SvelteTable` instance where I'm populating records from a file, prior to that I'm fetching records from my back-end for key comparison, I'd like to change the individual row background color based on non-matching keys from my back-end, I tried slots but it would only work for individual cells.

**Comment by bartektelec** [comment]
Please add code example of what you have so far

**Comment by Gildedter** [comment]
> Please add code example of what you have so far

Something like this:
```
<SvelteTable
  {...tableProps}
  let:cell
  let:column
  let:row
  on:clickRow={handleRowClick}
>
  <span slot="cell" class:active={row.isExpanded} class:err={column.key === "isDuplicate"}>
    {#if column.key === "stop"}
      {row.stop === "1" ? "Yes" : "No"}
    {:else if column.key === "remarks"}
      {row.remarks === null ? "None" : row["Remarks"]}
    {:else if column.key === "amount" || column.key === "balance" || column.key === "total"}
      {Number.parseFloat(cell).toLocaleString(undefined, {
        minimumFractionDigits: 2,
        maximumFractionDigits: 2,
      })}
    {:else}
      {cell}
    {/if}
  </span>
  <tr slot="expanded">
    <td colspan={tableProps.columns.length}>
      <SvelteTableWrapper2 source={row.stuff} />
    </td>
  </tr>
</SvelteTable>
<style lang="postcss">
  .active {
    @apply text-gray-900 underline;
  }
  .err {
    @apply bg-red-600;
  }
</style>
```
but I can only apply styles on the nested slot rather than the whole row

**Comment by bartektelec** [comment]
Sorry, this is something we don't manage on the library side, so far you can only apply slots to cells.
Do you have any ideas of how this could've been done or how you would like to handle it as a user?

**Comment by Gildedter** [comment]
I'd make a `tr` slot, but that wouldn't play well with the current component layout I think, not sure if its conceivable with just css variables, or adding a `style` key on the `row` instance i.e.:
```
let columns = [
  {
    key: 'id',
    title: 'ID'
  }
];
let rows = [
  {
    id: 1,
    status: true,
    style: [] // default value
  },
  {
    id: 2,
    status: false,
    style: ['inactive']
  }
];

<style lang="postcss">
.inactive{
@apply bg-red-300;
}
</style>
```

based on:
https://github.com/hurtigruten/svelte-table/blob/f9a7445bb5e73e2827ad3863f31de4b0ca905ec1/src/SvelteTable.svelte#L185

I imagine it like:
```
{@const styles = [...row.styles].join(" ")}
<tr
  class={`${assignedClasses.tr} ${isExpanded} ${isEvenOrOdd} ${styles}`}
  on:click={(event) => dispatch('clickRow', { event, row })}
>
```
