### ISSUE TITLE
Rows not reactive

### ISSUE THREAD

**Issue by Gildedter** [hurtigruten/svelte-table#44]
After loading rows (1st time), replacing rows (loading a new batch of rows) doesn't replace the previously loaded rows rendered, any work around for this?

**Comment by bartektelec** [comment]
Never had that issue.

Make sure you are correctly changing the state of `rows`. Object and array states should be viewed as immutable.
https://svelte.dev/tutorial/updating-arrays-and-objects

I can't help you more unless you provide a code snippet.

Let me know if this fixed your issue,

**Comment by Gildedter** [comment]
So uhh, the rows themselves are reactive, its just the pages that aren't, so in my test, I load 757 records first (rowsPerPage: 8), gives me 95-ish pages, then loading a new batch of 10 rows (same rowsPerPage), only gives me a total of 2 pages, I can still go to the third and so on pages (clicking `next` on the `pagination` control) even though I should only have two pages. How do I fix it?

**Comment by bartektelec** [comment]
You must be overwriting one of pagination related props, for async pagination example take a look at the demo repl in README.
